In [2]:
import pandas as pd
source_df=pd.read_csv("resources/pre_processed_data/train_noisy.csv")
source_df=source_df.rename(columns={'text':'original_text','re_text':'text'})

In [73]:
source_df

,ID,original_text,target,target_name,text
0,ynat-v1_train_00000,정i :파1 미사z KT( 이용기간 2e 단] Q분종U2보,4,IT과학,"정부, '주파수 미사용' KT에 이용기간 2년 단축 처분(종합2보)"
1,ynat-v1_train_00001,K찰.국DLwo 로L3한N% 회장 2 T0&}송=,3,사회,"경찰, '국회 불법 로비' 한어총 회장 등 20명 송치"
2,ynat-v1_train_00002,"m 김정) 자주통일 새,?r열1나가야1보",2,정치,"김정은 ""자주통일 새시대 열어나가야"""
3,ynat-v1_train_00004,pI美대선I앞두고 R2fr단 발] $비해 감시 강화,6,세계,"軍 ""美대선 앞두고 北 무수단 발사 대비해 감시 강화"""
4,ynat-v1_train_00006,프로야구~롯TKIAs광주 경기 y천취소,1,스포츠,프로야구 롯데-KIA 광주 경기 우천취소
...,...,...,...,...,...
1582,ynat-v1_train_02787,13이 노바 라이n2·미J어패0 T3 10 결G상품% *,6,세계,13일 노바 라이프미주 3개 품목 10% 할인 상품 출시
1583,ynat-v1_train_02788,남원소식 춘>X학%단+장Rn 모집,0,생활문화,남원소식 춘향단장 모집
1584,ynat-v1_train_02789,"이총리,세4. H직 완fl지 못해E할 일 꽤;남아",2,정치,"이총리, 세출 예산 완전 집행 못해 할 일 꽤 남아"
1585,ynat-v1_train_02792,"높`X#E율…}BO Q""[/선수 몸값 상승 CAO",1,스포츠,높은 취업률...선수 몸값 상승 논란
1586,ynat-v1_train_02797,텔레그램+한D 등h亞서 2시간H다운…C버T정gf39종!2보,4,IT과학,텔레그램 등 아시아서 2시간 다운...카카오뱅크 서비스 장애 39분 지속(2보)

In [3]:
import re
def delete_punctuations(text):
    text= re.sub(r'[!"#$%&\'()*+,-./:;<=>?@\[\]^_\`{|}~\\\\]','', text)
    return text

In [80]:
source_df['text']=source_df['text'].apply(delete_punctuations)

In [4]:
from googletrans import Translator
from tqdm import tqdm
import time

translator=Translator()

def backtranslate(text,src='ko',dest='en'):
    while True:
        try:
            res=translator.translate(text,src=src,dest=dest)
            return res.text
        except:
            time.sleep(2)
            continue

In [108]:
source_df['eng_text']=source_df['text'].apply(backtranslate)

In [110]:
source_df.to_csv("test.csv",encoding='utf-8-sig')

In [8]:
tqdm.pandas()

In [10]:
source_df['back_trans_txt']=source_df['eng_text'].progress_apply(lambda x : backtranslate(x,src='en',dest='ko'))

100%|██████████| 1587/1587 [27:56<00:00,  1.06s/it]

In [12]:
source_df.to_csv("test.csv",encoding='utf-8-sig')

In [13]:
source_df

,Unnamed: 0,ID,original_text,target,target_name,text,eng_text,back_trans_txt
0,0,ynat-v1_train_00000,정i :파1 미사z KT( 이용기간 2e 단] Q분종U2보,4,IT과학,정부 주파수 미사용 KT에 이용기간 2년 단축 처분종합2보,2 years of shortening of the use period for th...,정부 빈도 사용을위한 사용 기간의 2 년간의 단축 2 년
1,1,ynat-v1_train_00001,K찰.국DLwo 로L3한N% 회장 2 T0&}송=,3,사회,경찰 국회 불법 로비 한어총 회장 등 20명 송치,"20 people, including the president of the Nati...","국회 회장, 불법 로비 한국 어업을 포함한 20 명"
2,2,ynat-v1_train_00002,"m 김정) 자주통일 새,?r열1나가야1보",2,정치,김정은 자주통일 새시대 열어나가야,Kim Jong -un must open the unification new era,Kim Jong -un은 통일 새로운 시대를 열어야합니다
3,3,ynat-v1_train_00004,pI美대선I앞두고 R2fr단 발] $비해 감시 강화,6,세계,軍 美대선 앞두고 北 무수단 발사 대비해 감시 강화,Strengthening surveillance in preparation for ...,미국 대통령 선거를 앞두고 북한 수단 출시 준비를위한 감시 강화
4,4,ynat-v1_train_00006,프로야구~롯TKIAs광주 경기 y천취소,1,스포츠,프로야구 롯데KIA 광주 경기 우천취소,Professional baseball Lotte KIA KIA Gwangju Gy...,프로 야구 롯데 기아 기아 기아 왕 장주 경고 -도대 취소
...,...,...,...,...,...,...,...,...
1582,1582,ynat-v1_train_02787,13이 노바 라이n2·미J어패0 T3 10 결G상품% *,6,세계,13일 노바 라이프미주 3개 품목 10 할인 상품 출시,"Noba Life on the 13th, 3 items of 10 discount ...","13 일, 10 개의 할인 제품 3 개 항목의 Noba Life"
1583,1583,ynat-v1_train_02788,남원소식 춘>X학%단+장Rn 모집,0,생활문화,남원소식 춘향단장 모집,Namwon News Recruitment,Namwon 뉴스 모집
1584,1584,ynat-v1_train_02789,"이총리,세4. H직 완fl지 못해E할 일 꽤;남아",2,정치,이총리 세출 예산 완전 집행 못해 할 일 꽤 남아,Lee's expenditure budget is not fully executed,Lee의 지출 예산은 완전히 실행되지 않았습니다
1585,1585,ynat-v1_train_02792,"높`X#E율…}BO Q""[/선수 몸값 상승 CAO",1,스포츠,높은 취업률선수 몸값 상승 논란,High employment rate ransom controversy,높은 고용률 랜섬 논쟁
1586,1586,ynat-v1_train_02797,텔레그램+한D 등h亞서 2시간H다운…C버T정gf39종!2보,4,IT과학,텔레그램 등 아시아서 2시간 다운카카오뱅크 서비스 장애 39분 지속2보,2 -hour Kakao Bank Service Disorder 39 minutes...,"2- 카카오 은행 서비스 장애 39 분, 2 시간 등"

In [25]:
dest_df=source_df[['ID','target','target_name','back_trans_txt']].rename(columns={'back_trans_txt':'text'})

In [26]:
dest_df

,ID,target,target_name,text
0,ynat-v1_train_00000,4,IT과학,정부 빈도 사용을위한 사용 기간의 2 년간의 단축 2 년
1,ynat-v1_train_00001,3,사회,"국회 회장, 불법 로비 한국 어업을 포함한 20 명"
2,ynat-v1_train_00002,2,정치,Kim Jong -un은 통일 새로운 시대를 열어야합니다
3,ynat-v1_train_00004,6,세계,미국 대통령 선거를 앞두고 북한 수단 출시 준비를위한 감시 강화
4,ynat-v1_train_00006,1,스포츠,프로 야구 롯데 기아 기아 기아 왕 장주 경고 -도대 취소
...,...,...,...,...
1582,ynat-v1_train_02787,6,세계,"13 일, 10 개의 할인 제품 3 개 항목의 Noba Life"
1583,ynat-v1_train_02788,0,생활문화,Namwon 뉴스 모집
1584,ynat-v1_train_02789,2,정치,Lee의 지출 예산은 완전히 실행되지 않았습니다
1585,ynat-v1_train_02792,1,스포츠,높은 고용률 랜섬 논쟁
1586,ynat-v1_train_02797,4,IT과학,"2- 카카오 은행 서비스 장애 39 분, 2 시간 등"

In [27]:
source_df.drop(['Unnamed: 0','original_text','eng_text','back_trans_txt'],axis=1)

,ID,target,target_name,text
0,ynat-v1_train_00000,4,IT과학,정부 주파수 미사용 KT에 이용기간 2년 단축 처분종합2보
1,ynat-v1_train_00001,3,사회,경찰 국회 불법 로비 한어총 회장 등 20명 송치
2,ynat-v1_train_00002,2,정치,김정은 자주통일 새시대 열어나가야
3,ynat-v1_train_00004,6,세계,軍 美대선 앞두고 北 무수단 발사 대비해 감시 강화
4,ynat-v1_train_00006,1,스포츠,프로야구 롯데KIA 광주 경기 우천취소
...,...,...,...,...
1582,ynat-v1_train_02787,6,세계,13일 노바 라이프미주 3개 품목 10 할인 상품 출시
1583,ynat-v1_train_02788,0,생활문화,남원소식 춘향단장 모집
1584,ynat-v1_train_02789,2,정치,이총리 세출 예산 완전 집행 못해 할 일 꽤 남아
1585,ynat-v1_train_02792,1,스포츠,높은 취업률선수 몸값 상승 논란
1586,ynat-v1_train_02797,4,IT과학,텔레그램 등 아시아서 2시간 다운카카오뱅크 서비스 장애 39분 지속2보

In [29]:
final_output_df=pd.concat((dest_df,source_df.drop(['Unnamed: 0','original_text','eng_text','back_trans_txt'],axis=1)))

In [30]:
final_output_df.to_csv("dataset.csv",encoding='utf-8-sig')