In [5]:
import pandas as pd
data=pd.read_excel("wrong_predict_(2).xlsx",engine='openpyxl')

In [6]:
data

,Unnamed: 0,index,ID,text,target,target_name,source,similarity,predicted_value
0,13,378,ynat-v1_train_00087,"2023년 수능, 전국적으로 안정적인 진행... 학생들의 건강과 안전이 최우선입니다.",0,생활문화,noisy,0.16534,3
1,33,606,ynat-v1_train_00132,올해 경제 성장 전망에 대해 전문가들의 논평이 나오고 있다.,0,생활문화,noisy,0.19031,5
2,34,607,ynat-v1_train_00132,"바르셀로나를 떠나 빌바오에 합류한 메시, 축구계의 큰 파도.",0,생활문화,noisy,0.18133,1
3,35,608,ynat-v1_train_00132,올해 경제 성장률 전망에 대해 전문가들이 의견을 나누고 있다,0,생활문화,noisy,0.18269,5
4,40,619,ynat-v1_train_00135,"MLB 로키스, 피츠버그와 경기! 뉴에이지 메달리스트 감독 취임",0,생활문화,noisy,0.18749,1
...,...,...,...,...,...,...,...,...,...
906,937,10642,ynat-v1_train_02587,삼성전자가 갤럭시 S9 퀸툼의 새로운 버전을 출시합니다...AI로 업무 효율을 극대...,6,세계,noisy,0.19390,4
907,940,5830,ynat-v1_train_01346,"초등학교 3부 교육, 새로운 Y 교육 프로그램 도입",6,세계,noisy,0.17432,3
908,946,1504,ynat-v1_train_00379,"이서훈 국가정보원장이 ""민간단체와 협력해 헝가리의 인권 문제 해결""을 강조한다.",6,세계,noisy,0.20103,2
909,950,265,ynat-v1_train_00058,한 는 유 치료제 오 솔 美 임 본격화,6,세계,noisy,0.21316,4
910,953,5996,ynat-v1_train_01383,한미 정상회담 후 워싱턴서 새로운 협력 방안 논의,6,세계,noisy,0.19620,2

| Target | Predicted Value |
| --- | --- |
| 생활문화 0 | 스포츠 1 |
|   | 사회 3 |
| 정치 2 | 세계 6 |
| 사회 3 | 생활문화 0 |
|  | 경제 5 |
| IT과학 4 | 경제 5 |
| 경제 5 | IT과학 4 |
| 세계 6 | 정치 2 |
|  |  |

In [10]:
case_1=data.loc[(data['target']==0)&(data['predicted_value']==1),]
case_2=data.loc[(data['target']==0)&(data['predicted_value']==3),]

case_3=data.loc[(data['target']==2)&(data['predicted_value']==6),]

case_4=data.loc[(data['target']==3)&(data['predicted_value']==0),]
case_5=data.loc[(data['target']==3)&(data['predicted_value']==5),]


case_6=data.loc[(data['target']==4)&(data['predicted_value']==5),]
case_7=data.loc[(data['target']==5)&(data['predicted_value']==4),]

case_8=data.loc[(data['target']==6)&(data['predicted_value']==2),]

In [11]:
case_list=[case_1,case_2,case_3,case_4,case_5,case_6,case_7,case_8]

data_hard=pd.concat(case_list,ignore_index=True,axis=0)
data_hard

,Unnamed: 0,index,ID,text,target,target_name,source,similarity,predicted_value
0,34,607,ynat-v1_train_00132,"바르셀로나를 떠나 빌바오에 합류한 메시, 축구계의 큰 파도.",0,생활문화,noisy,0.18133,1
1,40,619,ynat-v1_train_00135,"MLB 로키스, 피츠버그와 경기! 뉴에이지 메달리스트 감독 취임",0,생활문화,noisy,0.18749,1
2,183,1798,ynat-v1_train_00458,"레까O!전, 축구 스타 J씨의 놀라운 돌파력",0,생활문화,noisy,0.20458,1
3,199,1987,ynat-v1_train_00498,"베테랑 코치, 6주 동안 패배, 팀 사기 낮추기.",0,생활문화,noisy,0.20547,1
4,211,2199,ynat-v1_train_00541,올림픽 대표팀 선발과 박예림의 선발로 강화했다.,0,생활문화,noisy,0.18657,1
...,...,...,...,...,...,...,...,...,...
396,879,2443,ynat-v1_train_00591,시진 낙 지 서 민생행보 까지 만 빈 해소,6,세계,noisy,0.19353,2
397,890,8285,ynat-v1_train_01984,시진핑은 북한 방문을 앞두고 시민 생활을 강화했다.,6,세계,noisy,0.21734,2
398,905,4267,ynat-v1_train_00998,"야권연대 성사, 총선 앞두고 정치판 흔들다",6,세계,noisy,0.18872,2
399,946,1504,ynat-v1_train_00379,"이서훈 국가정보원장이 ""민간단체와 협력해 헝가리의 인권 문제 해결""을 강조한다.",6,세계,noisy,0.20103,2
400,953,5996,ynat-v1_train_01383,한미 정상회담 후 워싱턴서 새로운 협력 방안 논의,6,세계,noisy,0.19620,2

In [12]:
data_hard.to_csv("hard_to_predict.csv",encoding='utf-8-sig')